name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf "$GITHUB_WORKSPACE" || true
          mkdir -p "$GITHUB_WORKSPACE"

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Cleanup Docker
        run: |
          docker compose down -v || true
          docker ps -aq | xargs -r docker rm -f || true
          docker network prune -f || true
          docker system prune -af || true

      - name: Build Docker images
        run: docker compose build

      - name: Run containers
        run: |
          docker compose up -d
          sleep 10
          curl -I http://localhost:9090 || true

      - name: Stop containers
        if: always()
        run: |
          docker stop dvna-app || true
          docker stop dvna-mysql || true

env:
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_RANDOM_ROOT_PASSWORD: ${{ secrets.MYSQL_RANDOM_ROOT_PASSWORD }}

