name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Clean workspace (force)
        run: |
          sudo rm -rf "$GITHUB_WORKSPACE" || true
          sudo mkdir -p "$GITHUB_WORKSPACE"
          sudo chown -R $USER:$USER "$GITHUB_WORKSPACE"

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Cleanup Docker
        run: |
          docker ps -aq | xargs -r docker rm -f || true
          docker network prune -f || true
          docker system prune -af || true

      - name: Run DVNA containers
        run: |
          docker run --rm --name dvna-mysql --env-file vars.env -d mysql:5.7
          sleep 10
          docker run --rm --name dvna-app --env-file vars.env --link dvna-mysql:mysql-db -p 9090:9090 -d appsecco/dvna
          sleep 10
          curl -I http://localhost:9090 || true

      - name: Stop containers
        if: always()
        run: |
          docker stop dvna-app || true
          docker stop dvna-mysql || true

env:
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_RANDOM_ROOT_PASSWORD: ${{ secrets.MYSQL_RANDOM_ROOT_PASSWORD }}
