name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start MySQL
        run: |
          docker run -d --name dvna-mysql --env-file vars.env mysql:5.7

      - name: Start DVNA app
        run: |
          docker run -d --name dvna-app --env-file vars.env --link dvna-mysql:mysql-db -p 9090:9090 appsecco/dvna

      - name: Wait for app to be ready
        run: |
          echo "Waiting for DVNA to start..."
          sleep 20
          curl -I http://localhost:9090 || exit 1

      - name: Stop containers
        if: always()
        run: |
          docker stop dvna-app || true
          docker stop dvna-mysql || true
