name: DAST with OWASP ZAP

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start MySQL
        run: |
          docker run -d --name dvna-mysql --env-file vars.env mysql:5.7

      - name: Start DVNA app
        run: |
          docker run -d --name dvna-app --env-file vars.env --link dvna-mysql:mysql-db -p 9090:9090 appsecco/dvna

      - name: Wait for app to be ready
        run: |
          echo "Waiting for DVNA to start..."
          sleep 20
          curl -I http://localhost:9090 || exit 1

      - name: ZAP Baseline Scan
        run: |
          docker run --rm --network="host" --user root -v $(pwd):/zap/wrk:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:9090 \
            -r zap-baseline-report.html \
            -w zap-baseline-report.md \
            -x zap-baseline-report.xml

      - name: ZAP Full Scan
        run: |
          docker run --rm --network="host" --user root -v $(pwd):/zap/wrk:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t http://localhost:9090 \
            -r zap-fullscan-report.html \
            -w zap-fullscan-report.md \
            -x zap-fullscan-report.xml


      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap-baseline-report.html
            zap-fullscan-report.html

      - name: Stop containers
        if: always()
        run: |
          docker stop dvna-app || true
          docker stop dvna-mysql || true
