name: DAST - ZAP

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start DVNA
        run: |
          docker compose -f docker-compose.yml up -d
          for i in {1..30}; do
            if curl -s http://localhost:9090 > /dev/null; then
              echo "DVNA is up!"
              break
            fi
            echo "Waiting for DVNA..."
            sleep 5
          done

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:9090"
          cmd_options: "-I -r zap-baseline.html"
          docker_name: ghcr.io/zaproxy/zaproxy:stable

      - name: Upload ZAP Baseline Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: zap-baseline.html

  zap-fullscan:
    runs-on: ubuntu-latest
    needs: zap-baseline
    steps:
      - uses: actions/checkout@v4

      - name: Start DVNA
        run: |
          docker compose -f docker-compose.yml up -d
          for i in {1..30}; do
            if curl -s http://localhost:9090 > /dev/null; then
              echo "DVNA is up!"
              break
            fi
            echo "Waiting for DVNA..."
            sleep 5
          done

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: "http://localhost:9090"
          cmd_options: "-I -r zap-fullscan.html"
          docker_name: ghcr.io/zaproxy/zaproxy:stable

      - name: Upload ZAP Full Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-fullscan-report
          path: zap-fullscan.html
