name: DAST ZAP Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  zap-scan:
    runs-on: self-hosted

    steps:
      - name: Start MySQL
        run: docker run -d --name dvna-mysql --env-file vars.env mysql:5.7

      - name: Start DVNA
        run: docker run -d --name dvna-app --env-file vars.env --link dvna-mysql:mysql-db -p 9090:9090 appsecco/dvna

      - name: Wait for app
        run: |
          for i in {1..10}; do
            curl -s http://localhost:9090 && break
            echo "Waiting for DVNA..."
            sleep 5
          done

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: http://localhost:9090
          cmd_options: -I -r zap-baseline.html
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          issue_title: ZAP Scan Baseline Report
          fail_action: false
          allow_issue_writing: true

      - name: Stop containers
        if: always()
        run: |
          docker stop dvna-app || true
          docker stop dvna-mysql || true
