name: "DAST ZAP"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  zap:
    runs-on: self-hosted
    steps:
      - name: Clean workspace (force)
        run: |
          sudo rm -rf "$GITHUB_WORKSPACE" || true
          sudo mkdir -p "$GITHUB_WORKSPACE"
          sudo chown -R $USER:$USER "$GITHUB_WORKSPACE"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Start DVNA
        run: |
          docker run --rm --name dvna-mysql --env-file vars.env -d mysql:5.7
          sleep 10
          docker run --rm --name dvna-app --env-file vars.env --link dvna-mysql:mysql-db -p 9090:9090 -d appsecco/dvna
          sleep 15
          curl -I http://localhost:9090 || true

      - name: Run ZAP Baseline Scan
        run: |
          docker run --network="host" \
            -v ${{ github.workspace }}:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://localhost:9090 -r zap-baseline.html -w zap-baseline.md -x zap-baseline.xml

      - name: Run ZAP Full Scan
        run: |
          docker run --network="host" \
            -v ${{ github.workspace }}:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py -t http://localhost:9090 -r zap-fullscan.html -w zap-fullscan.md -x zap-fullscan.xml

      - name: Upload ZAP Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap-baseline.html
            zap-baseline.md
            zap-baseline.xml
            zap-fullscan.html
            zap-fullscan.md
            zap-fullscan.xml

      - name: Stop DVNA
        if: always()
        run: |
          docker stop dvna-app || true
          docker stop dvna-mysql || true
