name: ZAP

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  zap-baseline:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start DVNA
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Wait for app
        run: |
          for i in {1..60}; do
            if curl -sSf http://localhost:9090 > /dev/null; then
              echo "DVNA is up!"
              exit 0
            fi
            echo "Waiting for DVNA..."
            sleep 5
          done
          echo "DVNA failed to start"
          exit 1

      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/zap/wrk" \
            -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://host.docker.internal:9090 \
            -r zap-baseline.html \
            -x zap-baseline.xml \
            -w zap-baseline.md || true

      - name: Upload ZAP Baseline artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: |
            ${{ github.workspace }}/zap-baseline.html
            ${{ github.workspace }}/zap-baseline.xml
            ${{ github.workspace }}/zap-baseline.md

      - name: Stop DVNA
        run: docker compose -f docker-compose.yml down

  zap-full:
    runs-on: self-hosted
    needs: zap-baseline
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start DVNA
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Wait for app
        run: |
          for i in {1..60}; do
            if curl -sSf http://localhost:9090 > /dev/null; then
              echo "DVNA is up!"
              exit 0
            fi
            echo "Waiting for DVNA..."
            sleep 5
          done
          echo "DVNA failed to start"
          exit 1

      - name: Run ZAP Full Scan
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/zap/wrk" \
            -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t http://host.docker.internal:9090 \
            -r zap-full.html \
            -x zap-full.xml \
            -w zap-full.md || true

      - name: Upload ZAP Full Scan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-full-report
          path: |
            ${{ github.workspace }}/zap-full.html
            ${{ github.workspace }}/zap-full.xml
            ${{ github.workspace }}/zap-full.md

      - name: Stop DVNA
        run: docker compose -f docker-compose.yml down
