name: Security Checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan repository for secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-format sarif --report-path gitleaks-results.sarif

      - name: Build DVNA image
        run: |
          docker build -t dvna-app .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: dvna-app
          format: 'table'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'
          output: trivy-image-report.txt

      - name: Scan configs with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'
          format: 'table'
          output: trivy-config-report.txt

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Run npm audit
        run: npm audit --json > npm-audit-report.json || true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            gitleaks-results.sarif
            trivy-image-report.txt
            trivy-config-report.txt
            npm-audit-report.json
