name: SAST: Semgrep

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep via Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/src" \
            semgrep/semgrep \
            semgrep scan --sarif --output=semgrep.sarif --config=p/ci || true

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
