name: "Semgrep SAST"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Semgrep via Docker
        run: |
          docker run --rm -v "$PWD:/src" semgrep/semgrep:latest \
            semgrep \
              --config p/owasp-top-ten \
              --config p/javascript \
              --error --strict --timeout 0 \
              --exclude node_modules \
              --exclude docs \
              --sarif --output semgrep.sarif

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep.sarif
